# golangci-lint configuration file
# This ensures consistent linting behavior locally and in CI/CD

run:
  timeout: 5m
  tests: true
  # Include test files in linting
  build-tags:
    - integration

linters:
  enable:
    # Enabled by default
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter
    - unused        # Check for unused code
    
    # Additional recommended linters for SDK quality
    - gofmt         # Check code formatting
    - goimports     # Check import formatting
    - misspell      # Find commonly misspelled words
    - revive        # Fast, configurable linter
    - unconvert     # Remove unnecessary type conversions
    
  disable:
    # Disabled to avoid noise - can be enabled selectively later
    - exhaustruct   # Too strict for test structs
    - funlen        # Function length checks can be too strict
    - nlreturn      # Newline return can be stylistic
    - paralleltest  # Not all tests need to be parallel
    - wsl           # Whitespace linter can be too opinionated
    - testifylint   # Can be overly strict about testify usage

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
    
  govet:
    enable-all: true
    disable:
      - shadow  # Can be overly strict
      
  staticcheck:
    checks: ["all"]
    
  gofmt:
    simplify: true
    
  goimports:
    local-prefixes: github.com/pingidentity/pingone-go-client
    
  misspell:
    locale: US
    
  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: indent-error-flow
      - name: superfluous-else
      - name: unreachable-code
      - name: unused-parameter

issues:
  # Exclude specific issues in generated code
  exclude-dirs:
    - vendor
  
  exclude-files:
    - "pingone/.*\\.go$"  # Exclude generated code in pingone directory
  
  # Maximum issues count per one linter
  max-issues-per-linter: 0
  
  # Maximum count of issues with the same text
  max-same-issues: 0
  
  # Show all issues
  exclude-use-default: false
  
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec
        - goconst
