// Copyright © 2025 Ping Identity Corporation
/*
PingOne Platform User and Configuration Management API - SDK Generator

PingOne is a cloud-based framework for secure identity access management. The PingOne API gives developers the tools to integrate enterprise and third-party applications with the PingOne platform.

Contact: devex@pingidentity.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingone

import (
	"encoding/json"
	"fmt"
)

// DaVinciFlowSettingsRequestRequireAuthenticationToInitiate - struct for DaVinciFlowSettingsRequestRequireAuthenticationToInitiate
type DaVinciFlowSettingsRequestRequireAuthenticationToInitiate struct {
	DaVinciFlowSettingsRequestRequireAuthenticationToInitiateChoice2 *DaVinciFlowSettingsRequestRequireAuthenticationToInitiateChoice2
	Bool                                                             *bool
}

// DaVinciFlowSettingsRequestRequireAuthenticationToInitiateChoice2AsDaVinciFlowSettingsRequestRequireAuthenticationToInitiate is a convenience function that returns DaVinciFlowSettingsRequestRequireAuthenticationToInitiateChoice2 wrapped in DaVinciFlowSettingsRequestRequireAuthenticationToInitiate
func DaVinciFlowSettingsRequestRequireAuthenticationToInitiateChoice2AsDaVinciFlowSettingsRequestRequireAuthenticationToInitiate(v *DaVinciFlowSettingsRequestRequireAuthenticationToInitiateChoice2) DaVinciFlowSettingsRequestRequireAuthenticationToInitiate {
	return DaVinciFlowSettingsRequestRequireAuthenticationToInitiate{
		DaVinciFlowSettingsRequestRequireAuthenticationToInitiateChoice2: v,
	}
}

// boolAsDaVinciFlowSettingsRequestRequireAuthenticationToInitiate is a convenience function that returns bool wrapped in DaVinciFlowSettingsRequestRequireAuthenticationToInitiate
func BoolAsDaVinciFlowSettingsRequestRequireAuthenticationToInitiate(v *bool) DaVinciFlowSettingsRequestRequireAuthenticationToInitiate {
	return DaVinciFlowSettingsRequestRequireAuthenticationToInitiate{
		Bool: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *DaVinciFlowSettingsRequestRequireAuthenticationToInitiate) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into DaVinciFlowSettingsRequestRequireAuthenticationToInitiateChoice2
	err = json.Unmarshal(data, &dst.DaVinciFlowSettingsRequestRequireAuthenticationToInitiateChoice2)
	if err == nil {
		jsonDaVinciFlowSettingsRequestRequireAuthenticationToInitiateChoice2, _ := json.Marshal(dst.DaVinciFlowSettingsRequestRequireAuthenticationToInitiateChoice2)
		if string(jsonDaVinciFlowSettingsRequestRequireAuthenticationToInitiateChoice2) == "{}" { // empty struct
			dst.DaVinciFlowSettingsRequestRequireAuthenticationToInitiateChoice2 = nil
		} else {
			match++
		}
	} else {
		dst.DaVinciFlowSettingsRequestRequireAuthenticationToInitiateChoice2 = nil
	}

	// try to unmarshal data into Bool
	err = json.Unmarshal(data, &dst.Bool)
	if err == nil {
		jsonBool, _ := json.Marshal(dst.Bool)
		if string(jsonBool) == "{}" { // empty struct
			dst.Bool = nil
		} else {
			match++
		}
	} else {
		dst.Bool = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.DaVinciFlowSettingsRequestRequireAuthenticationToInitiateChoice2 = nil
		dst.Bool = nil

		return fmt.Errorf("data matches more than one schema in oneOf(DaVinciFlowSettingsRequestRequireAuthenticationToInitiate)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(DaVinciFlowSettingsRequestRequireAuthenticationToInitiate)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src DaVinciFlowSettingsRequestRequireAuthenticationToInitiate) MarshalJSON() ([]byte, error) {
	if src.DaVinciFlowSettingsRequestRequireAuthenticationToInitiateChoice2 != nil {
		return json.Marshal(&src.DaVinciFlowSettingsRequestRequireAuthenticationToInitiateChoice2)
	}

	if src.Bool != nil {
		return json.Marshal(&src.Bool)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *DaVinciFlowSettingsRequestRequireAuthenticationToInitiate) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.DaVinciFlowSettingsRequestRequireAuthenticationToInitiateChoice2 != nil {
		return obj.DaVinciFlowSettingsRequestRequireAuthenticationToInitiateChoice2
	}

	if obj.Bool != nil {
		return obj.Bool
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj DaVinciFlowSettingsRequestRequireAuthenticationToInitiate) GetActualInstanceValue() interface{} {
	if obj.DaVinciFlowSettingsRequestRequireAuthenticationToInitiateChoice2 != nil {
		return *obj.DaVinciFlowSettingsRequestRequireAuthenticationToInitiateChoice2
	}

	if obj.Bool != nil {
		return *obj.Bool
	}

	// all schemas are nil
	return nil
}

type NullableDaVinciFlowSettingsRequestRequireAuthenticationToInitiate struct {
	value *DaVinciFlowSettingsRequestRequireAuthenticationToInitiate
	isSet bool
}

func (v NullableDaVinciFlowSettingsRequestRequireAuthenticationToInitiate) Get() *DaVinciFlowSettingsRequestRequireAuthenticationToInitiate {
	return v.value
}

func (v *NullableDaVinciFlowSettingsRequestRequireAuthenticationToInitiate) Set(val *DaVinciFlowSettingsRequestRequireAuthenticationToInitiate) {
	v.value = val
	v.isSet = true
}

func (v NullableDaVinciFlowSettingsRequestRequireAuthenticationToInitiate) IsSet() bool {
	return v.isSet
}

func (v *NullableDaVinciFlowSettingsRequestRequireAuthenticationToInitiate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDaVinciFlowSettingsRequestRequireAuthenticationToInitiate(val *DaVinciFlowSettingsRequestRequireAuthenticationToInitiate) *NullableDaVinciFlowSettingsRequestRequireAuthenticationToInitiate {
	return &NullableDaVinciFlowSettingsRequestRequireAuthenticationToInitiate{value: val, isSet: true}
}

func (v NullableDaVinciFlowSettingsRequestRequireAuthenticationToInitiate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDaVinciFlowSettingsRequestRequireAuthenticationToInitiate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
