// Copyright © 2025 Ping Identity Corporation
/*
PingOne Platform User and Configuration Management API - SDK Generator

PingOne is a cloud-based framework for secure identity access management. The PingOne API gives developers the tools to integrate enterprise and third-party applications with the PingOne platform.

Contact: devex@pingidentity.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingone

import (
	"encoding/json"
	"log/slog"
)

// checks if the DaVinciFlowReplaceRequestTriggerConfigurationMFA type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DaVinciFlowReplaceRequestTriggerConfigurationMFA{}

// checks if the DaVinciFlowReplaceRequestTriggerConfigurationMFA type satisfies the LogValuer interface at compile time
var _ slog.LogValuer = &DaVinciFlowReplaceRequestTriggerConfigurationMFA{}

// DaVinciFlowReplaceRequestTriggerConfigurationMFA struct for DaVinciFlowReplaceRequestTriggerConfigurationMFA
type DaVinciFlowReplaceRequestTriggerConfigurationMFA struct {
	Enabled              *bool    `json:"enabled,omitempty"`
	Time                 *float32 `json:"time,omitempty"`
	TimeFormat           *string  `json:"timeFormat,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DaVinciFlowReplaceRequestTriggerConfigurationMFA DaVinciFlowReplaceRequestTriggerConfigurationMFA

// NewDaVinciFlowReplaceRequestTriggerConfigurationMFA instantiates a new DaVinciFlowReplaceRequestTriggerConfigurationMFA object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDaVinciFlowReplaceRequestTriggerConfigurationMFA() *DaVinciFlowReplaceRequestTriggerConfigurationMFA {
	this := DaVinciFlowReplaceRequestTriggerConfigurationMFA{}
	return &this
}

// NewDaVinciFlowReplaceRequestTriggerConfigurationMFAWithDefaults instantiates a new DaVinciFlowReplaceRequestTriggerConfigurationMFA object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDaVinciFlowReplaceRequestTriggerConfigurationMFAWithDefaults() *DaVinciFlowReplaceRequestTriggerConfigurationMFA {
	this := DaVinciFlowReplaceRequestTriggerConfigurationMFA{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *DaVinciFlowReplaceRequestTriggerConfigurationMFA) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DaVinciFlowReplaceRequestTriggerConfigurationMFA) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *DaVinciFlowReplaceRequestTriggerConfigurationMFA) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *DaVinciFlowReplaceRequestTriggerConfigurationMFA) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *DaVinciFlowReplaceRequestTriggerConfigurationMFA) GetTime() float32 {
	if o == nil || IsNil(o.Time) {
		var ret float32
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DaVinciFlowReplaceRequestTriggerConfigurationMFA) GetTimeOk() (*float32, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *DaVinciFlowReplaceRequestTriggerConfigurationMFA) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given float32 and assigns it to the Time field.
func (o *DaVinciFlowReplaceRequestTriggerConfigurationMFA) SetTime(v float32) {
	o.Time = &v
}

// GetTimeFormat returns the TimeFormat field value if set, zero value otherwise.
func (o *DaVinciFlowReplaceRequestTriggerConfigurationMFA) GetTimeFormat() string {
	if o == nil || IsNil(o.TimeFormat) {
		var ret string
		return ret
	}
	return *o.TimeFormat
}

// GetTimeFormatOk returns a tuple with the TimeFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DaVinciFlowReplaceRequestTriggerConfigurationMFA) GetTimeFormatOk() (*string, bool) {
	if o == nil || IsNil(o.TimeFormat) {
		return nil, false
	}
	return o.TimeFormat, true
}

// HasTimeFormat returns a boolean if a field has been set.
func (o *DaVinciFlowReplaceRequestTriggerConfigurationMFA) HasTimeFormat() bool {
	if o != nil && !IsNil(o.TimeFormat) {
		return true
	}

	return false
}

// SetTimeFormat gets a reference to the given string and assigns it to the TimeFormat field.
func (o *DaVinciFlowReplaceRequestTriggerConfigurationMFA) SetTimeFormat(v string) {
	o.TimeFormat = &v
}

func (o DaVinciFlowReplaceRequestTriggerConfigurationMFA) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DaVinciFlowReplaceRequestTriggerConfigurationMFA) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	if !IsNil(o.TimeFormat) {
		toSerialize["timeFormat"] = o.TimeFormat
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DaVinciFlowReplaceRequestTriggerConfigurationMFA) UnmarshalJSON(data []byte) (err error) {
	varDaVinciFlowReplaceRequestTriggerConfigurationMFA := _DaVinciFlowReplaceRequestTriggerConfigurationMFA{}

	err = json.Unmarshal(data, &varDaVinciFlowReplaceRequestTriggerConfigurationMFA)

	if err != nil {
		return err
	}

	*o = DaVinciFlowReplaceRequestTriggerConfigurationMFA(varDaVinciFlowReplaceRequestTriggerConfigurationMFA)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "enabled")
		delete(additionalProperties, "time")
		delete(additionalProperties, "timeFormat")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

func (o DaVinciFlowReplaceRequestTriggerConfigurationMFA) LogValue() slog.Value {
	logAttrs := make([]slog.Attr, 0)

	if !IsNil(o.Enabled) {
		logAttrs = append(logAttrs, slog.Any("enabled", *o.Enabled))
	}
	if !IsNil(o.Time) {
		logAttrs = append(logAttrs, slog.Any("time", *o.Time))
	}
	if !IsNil(o.TimeFormat) {
		logAttrs = append(logAttrs, slog.Any("timeFormat", *o.TimeFormat))
	}
	logAttrs = append(logAttrs, slog.Any("additionalProperties", o.AdditionalProperties))

	return slog.GroupValue(logAttrs...)
}

type NullableDaVinciFlowReplaceRequestTriggerConfigurationMFA struct {
	value *DaVinciFlowReplaceRequestTriggerConfigurationMFA
	isSet bool
}

func (v NullableDaVinciFlowReplaceRequestTriggerConfigurationMFA) Get() *DaVinciFlowReplaceRequestTriggerConfigurationMFA {
	return v.value
}

func (v *NullableDaVinciFlowReplaceRequestTriggerConfigurationMFA) Set(val *DaVinciFlowReplaceRequestTriggerConfigurationMFA) {
	v.value = val
	v.isSet = true
}

func (v NullableDaVinciFlowReplaceRequestTriggerConfigurationMFA) IsSet() bool {
	return v.isSet
}

func (v *NullableDaVinciFlowReplaceRequestTriggerConfigurationMFA) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDaVinciFlowReplaceRequestTriggerConfigurationMFA(val *DaVinciFlowReplaceRequestTriggerConfigurationMFA) *NullableDaVinciFlowReplaceRequestTriggerConfigurationMFA {
	return &NullableDaVinciFlowReplaceRequestTriggerConfigurationMFA{value: val, isSet: true}
}

func (v NullableDaVinciFlowReplaceRequestTriggerConfigurationMFA) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDaVinciFlowReplaceRequestTriggerConfigurationMFA) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}