// Copyright © 2025 Ping Identity Corporation
/*
PingOne Platform User and Configuration Management API - SDK Generator

PingOne is a cloud-based framework for secure identity access management. The PingOne API gives developers the tools to integrate enterprise and third-party applications with the PingOne platform.

Contact: devex@pingidentity.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingone

import (
	"encoding/json"
	"log/slog"
)

// checks if the DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage{}

// checks if the DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage type satisfies the LogValuer interface at compile time
var _ slog.LogValuer = &DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage{}

// DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage struct for DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage
type DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage struct {
	Value                *string `json:"value,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage

// NewDaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage instantiates a new DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage() *DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage {
	this := DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage{}
	return &this
}

// NewDaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessageWithDefaults instantiates a new DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessageWithDefaults() *DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage {
	this := DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage) SetValue(v string) {
	o.Value = &v
}

func (o DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage) UnmarshalJSON(data []byte) (err error) {

	varDaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage := _DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage{}

	err = json.Unmarshal(data, &varDaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage)

	if err != nil {
		return err
	}

	*o = DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage(varDaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

func (o DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage) LogValue() slog.Value {
	logAttrs := make([]slog.Attr, 0)

	if !IsNil(o.Value) {
		logAttrs = append(logAttrs, slog.Any("value", *o.Value))
	}
	logAttrs = append(logAttrs, slog.Any("additionalProperties", o.AdditionalProperties))

	return slog.GroupValue(logAttrs...)
}

type NullableDaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage struct {
	value *DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage
	isSet bool
}

func (v NullableDaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage) Get() *DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage {
	return v.value
}

func (v *NullableDaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage) Set(val *DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableDaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableDaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage(val *DaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage) *NullableDaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage {
	return &NullableDaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage{value: val, isSet: true}
}

func (v NullableDaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDaVinciFlowGraphDataRequestElementsNodeDataPropertiesMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
