// Copyright © 2025 Ping Identity Corporation
/*
PingOne Platform User and Configuration Management API - Go SDK

PingOne is a cloud-based framework for secure identity access management. The PingOne API gives developers the tools to integrate enterprise and third-party applications with the PingOne platform.

Contact: developerexperiences@pingidentity.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingone

import (
	"encoding/json"
	"fmt"
	"log/slog"
)

// checks if the DaVinciFlowPolicyEventsCollectionEmbedded type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DaVinciFlowPolicyEventsCollectionEmbedded{}

// checks if the DaVinciFlowPolicyEventsCollectionEmbedded type satisfies the LogValuer interface at compile time
var _ slog.LogValuer = &DaVinciFlowPolicyEventsCollectionEmbedded{}

// DaVinciFlowPolicyEventsCollectionEmbedded struct for DaVinciFlowPolicyEventsCollectionEmbedded
type DaVinciFlowPolicyEventsCollectionEmbedded struct {
	Events               []DaVinciFlowPolicyEventsCollectionEmbeddedEvent `json:"events"`
	AdditionalProperties map[string]interface{}
}

type _DaVinciFlowPolicyEventsCollectionEmbedded DaVinciFlowPolicyEventsCollectionEmbedded

// NewDaVinciFlowPolicyEventsCollectionEmbedded instantiates a new DaVinciFlowPolicyEventsCollectionEmbedded object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDaVinciFlowPolicyEventsCollectionEmbedded(events []DaVinciFlowPolicyEventsCollectionEmbeddedEvent) *DaVinciFlowPolicyEventsCollectionEmbedded {
	this := DaVinciFlowPolicyEventsCollectionEmbedded{}
	this.Events = events
	return &this
}

// NewDaVinciFlowPolicyEventsCollectionEmbeddedWithDefaults instantiates a new DaVinciFlowPolicyEventsCollectionEmbedded object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDaVinciFlowPolicyEventsCollectionEmbeddedWithDefaults() *DaVinciFlowPolicyEventsCollectionEmbedded {
	this := DaVinciFlowPolicyEventsCollectionEmbedded{}
	return &this
}

// GetEvents returns the Events field value
func (o *DaVinciFlowPolicyEventsCollectionEmbedded) GetEvents() []DaVinciFlowPolicyEventsCollectionEmbeddedEvent {
	if o == nil {
		var ret []DaVinciFlowPolicyEventsCollectionEmbeddedEvent
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *DaVinciFlowPolicyEventsCollectionEmbedded) GetEventsOk() ([]DaVinciFlowPolicyEventsCollectionEmbeddedEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *DaVinciFlowPolicyEventsCollectionEmbedded) SetEvents(v []DaVinciFlowPolicyEventsCollectionEmbeddedEvent) {
	o.Events = v
}

func (o DaVinciFlowPolicyEventsCollectionEmbedded) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DaVinciFlowPolicyEventsCollectionEmbedded) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["events"] = o.Events

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DaVinciFlowPolicyEventsCollectionEmbedded) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDaVinciFlowPolicyEventsCollectionEmbedded := _DaVinciFlowPolicyEventsCollectionEmbedded{}

	err = json.Unmarshal(data, &varDaVinciFlowPolicyEventsCollectionEmbedded)

	if err != nil {
		return err
	}

	*o = DaVinciFlowPolicyEventsCollectionEmbedded(varDaVinciFlowPolicyEventsCollectionEmbedded)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "events")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

func (o DaVinciFlowPolicyEventsCollectionEmbedded) LogValue() slog.Value {
	logAttrs := make([]slog.Attr, 0)

	logAttrs = append(logAttrs, slog.Any("events", o.Events))
	logAttrs = append(logAttrs, slog.Any("additionalProperties", o.AdditionalProperties))

	return slog.GroupValue(logAttrs...)
}

type NullableDaVinciFlowPolicyEventsCollectionEmbedded struct {
	value *DaVinciFlowPolicyEventsCollectionEmbedded
	isSet bool
}

func (v NullableDaVinciFlowPolicyEventsCollectionEmbedded) Get() *DaVinciFlowPolicyEventsCollectionEmbedded {
	return v.value
}

func (v *NullableDaVinciFlowPolicyEventsCollectionEmbedded) Set(val *DaVinciFlowPolicyEventsCollectionEmbedded) {
	v.value = val
	v.isSet = true
}

func (v NullableDaVinciFlowPolicyEventsCollectionEmbedded) IsSet() bool {
	return v.isSet
}

func (v *NullableDaVinciFlowPolicyEventsCollectionEmbedded) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDaVinciFlowPolicyEventsCollectionEmbedded(val *DaVinciFlowPolicyEventsCollectionEmbedded) *NullableDaVinciFlowPolicyEventsCollectionEmbedded {
	return &NullableDaVinciFlowPolicyEventsCollectionEmbedded{value: val, isSet: true}
}

func (v NullableDaVinciFlowPolicyEventsCollectionEmbedded) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDaVinciFlowPolicyEventsCollectionEmbedded) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
