// Copyright © 2025 Ping Identity Corporation
/*
PingOne Platform User and Configuration Management API - SDK Generator

PingOne is a cloud-based framework for secure identity access management. The PingOne API gives developers the tools to integrate enterprise and third-party applications with the PingOne platform.

Contact: devex@pingidentity.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingone

import (
	"encoding/json"
	"fmt"
)

// DaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2 the model 'DaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2'
type DaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2 string

// List of DaVinci_Flow_Settings_Response_Use_Intermediate_Loading_Screen_Choice_2
const (
	DAVINCIFLOWSETTINGSRESPONSEUSEINTERMEDIATELOADINGSCREENCHOICE2_FALSE DaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2 = "false"
	DAVINCIFLOWSETTINGSRESPONSEUSEINTERMEDIATELOADINGSCREENCHOICE2_TRUE  DaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2 = "true"
)

// All allowed values of DaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2 enum
var AllowedDaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2EnumValues = []DaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2{
	"false",
	"true",
}

func (v *DaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2(value)
	for _, existing := range AllowedDaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2EnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = DaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2(fmt.Sprintf("%s", value))
	return nil
}

// NewDaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2FromValue returns a pointer to a valid DaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2FromValue(v string) (*DaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2, error) {
	ev := DaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2: valid values are %v", v, AllowedDaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2EnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2) IsValid() bool {
	for _, existing := range AllowedDaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2EnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DaVinci_Flow_Settings_Response_Use_Intermediate_Loading_Screen_Choice_2 value
func (v DaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2) Ptr() *DaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2 {
	return &v
}

type NullableDaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2 struct {
	value *DaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2
	isSet bool
}

func (v NullableDaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2) Get() *DaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2 {
	return v.value
}

func (v *NullableDaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2) Set(val *DaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2) {
	v.value = val
	v.isSet = true
}

func (v NullableDaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2) IsSet() bool {
	return v.isSet
}

func (v *NullableDaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2(val *DaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2) *NullableDaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2 {
	return &NullableDaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2{value: val, isSet: true}
}

func (v NullableDaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDaVinciFlowSettingsResponseUseIntermediateLoadingScreenChoice2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
