// Copyright © 2025 Ping Identity Corporation
/*
PingOne Platform User and Configuration Management API - SDK Generator

PingOne is a cloud-based framework for secure identity access management. The PingOne API gives developers the tools to integrate enterprise and third-party applications with the PingOne platform.

Contact: devex@pingidentity.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingone

import (
	"encoding/json"
	"fmt"
	"log/slog"
)

// checks if the DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton{}

// checks if the DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton type satisfies the LogValuer interface at compile time
var _ slog.LogValuer = &DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton{}

// DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton struct for DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton
type DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton struct {
	Value                bool `json:"value"`
	AdditionalProperties map[string]interface{}
}

type _DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton

// NewDaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton instantiates a new DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton(value bool) *DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton {
	this := DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton{}
	this.Value = value
	return &this
}

// NewDaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButtonWithDefaults instantiates a new DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButtonWithDefaults() *DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton {
	this := DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton{}
	return &this
}

// GetValue returns the Value field value
func (o *DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton) GetValue() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton) GetValueOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton) SetValue(v bool) {
	o.Value = v
}

func (o DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v in model_da_vinci_flow_graph_data_request_elements_node_data_properties_show_continue_button.go", requiredProperty)
		}
	}

	varDaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton := _DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton{}

	err = json.Unmarshal(data, &varDaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton)

	if err != nil {
		return err
	}

	*o = DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton(varDaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

func (o DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton) LogValue() slog.Value {
	logAttrs := make([]slog.Attr, 0)

	logAttrs = append(logAttrs, slog.Any("value", o.Value))
	logAttrs = append(logAttrs, slog.Any("additionalProperties", o.AdditionalProperties))

	return slog.GroupValue(logAttrs...)
}

type NullableDaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton struct {
	value *DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton
	isSet bool
}

func (v NullableDaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton) Get() *DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton {
	return v.value
}

func (v *NullableDaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton) Set(val *DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton) {
	v.value = val
	v.isSet = true
}

func (v NullableDaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton) IsSet() bool {
	return v.isSet
}

func (v *NullableDaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton(val *DaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton) *NullableDaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton {
	return &NullableDaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton{value: val, isSet: true}
}

func (v NullableDaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDaVinciFlowGraphDataRequestElementsNodeDataPropertiesShowContinueButton) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
