// Copyright © 2025 Ping Identity Corporation
/*
PingOne Platform User and Configuration Management API - SDK Generator

PingOne is a cloud-based framework for secure identity access management. The PingOne API gives developers the tools to integrate enterprise and third-party applications with the PingOne platform.

Contact: devex@pingidentity.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingone

import (
	"encoding/json"
	"log/slog"
)

// checks if the DaVinciApplicationReplaceRequestApiKey type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DaVinciApplicationReplaceRequestApiKey{}

// checks if the DaVinciApplicationReplaceRequestApiKey type satisfies the LogValuer interface at compile time
var _ slog.LogValuer = &DaVinciApplicationReplaceRequestApiKey{}

// DaVinciApplicationReplaceRequestApiKey struct for DaVinciApplicationReplaceRequestApiKey
type DaVinciApplicationReplaceRequestApiKey struct {
	Enabled              *bool `json:"enabled,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DaVinciApplicationReplaceRequestApiKey DaVinciApplicationReplaceRequestApiKey

// NewDaVinciApplicationReplaceRequestApiKey instantiates a new DaVinciApplicationReplaceRequestApiKey object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDaVinciApplicationReplaceRequestApiKey() *DaVinciApplicationReplaceRequestApiKey {
	this := DaVinciApplicationReplaceRequestApiKey{}
	return &this
}

// NewDaVinciApplicationReplaceRequestApiKeyWithDefaults instantiates a new DaVinciApplicationReplaceRequestApiKey object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDaVinciApplicationReplaceRequestApiKeyWithDefaults() *DaVinciApplicationReplaceRequestApiKey {
	this := DaVinciApplicationReplaceRequestApiKey{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *DaVinciApplicationReplaceRequestApiKey) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DaVinciApplicationReplaceRequestApiKey) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *DaVinciApplicationReplaceRequestApiKey) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *DaVinciApplicationReplaceRequestApiKey) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o DaVinciApplicationReplaceRequestApiKey) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DaVinciApplicationReplaceRequestApiKey) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DaVinciApplicationReplaceRequestApiKey) UnmarshalJSON(data []byte) (err error) {
	varDaVinciApplicationReplaceRequestApiKey := _DaVinciApplicationReplaceRequestApiKey{}

	err = json.Unmarshal(data, &varDaVinciApplicationReplaceRequestApiKey)

	if err != nil {
		return err
	}

	*o = DaVinciApplicationReplaceRequestApiKey(varDaVinciApplicationReplaceRequestApiKey)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "enabled")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

func (o DaVinciApplicationReplaceRequestApiKey) LogValue() slog.Value {
	logAttrs := make([]slog.Attr, 0)

	if !IsNil(o.Enabled) {
		logAttrs = append(logAttrs, slog.Any("enabled", *o.Enabled))
	}
	logAttrs = append(logAttrs, slog.Any("additionalProperties", o.AdditionalProperties))

	return slog.GroupValue(logAttrs...)
}

type NullableDaVinciApplicationReplaceRequestApiKey struct {
	value *DaVinciApplicationReplaceRequestApiKey
	isSet bool
}

func (v NullableDaVinciApplicationReplaceRequestApiKey) Get() *DaVinciApplicationReplaceRequestApiKey {
	return v.value
}

func (v *NullableDaVinciApplicationReplaceRequestApiKey) Set(val *DaVinciApplicationReplaceRequestApiKey) {
	v.value = val
	v.isSet = true
}

func (v NullableDaVinciApplicationReplaceRequestApiKey) IsSet() bool {
	return v.isSet
}

func (v *NullableDaVinciApplicationReplaceRequestApiKey) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDaVinciApplicationReplaceRequestApiKey(val *DaVinciApplicationReplaceRequestApiKey) *NullableDaVinciApplicationReplaceRequestApiKey {
	return &NullableDaVinciApplicationReplaceRequestApiKey{value: val, isSet: true}
}

func (v NullableDaVinciApplicationReplaceRequestApiKey) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDaVinciApplicationReplaceRequestApiKey) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
