// Copyright © 2025 Ping Identity Corporation
/*
PingOne Platform User and Configuration Management API - SDK Generator

PingOne is a cloud-based framework for secure identity access management. The PingOne API gives developers the tools to integrate enterprise and third-party applications with the PingOne platform.

Contact: devex@pingidentity.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingone

import (
	"encoding/json"
	"fmt"
)

// DaVinciFlowSettingsResponseUseCustomScript - struct for DaVinciFlowSettingsResponseUseCustomScript
type DaVinciFlowSettingsResponseUseCustomScript struct {
	DaVinciFlowSettingsResponseUseCustomScriptChoice2 *DaVinciFlowSettingsResponseUseCustomScriptChoice2
	Bool                                              *bool
}

// DaVinciFlowSettingsResponseUseCustomScriptChoice2AsDaVinciFlowSettingsResponseUseCustomScript is a convenience function that returns DaVinciFlowSettingsResponseUseCustomScriptChoice2 wrapped in DaVinciFlowSettingsResponseUseCustomScript
func DaVinciFlowSettingsResponseUseCustomScriptChoice2AsDaVinciFlowSettingsResponseUseCustomScript(v *DaVinciFlowSettingsResponseUseCustomScriptChoice2) DaVinciFlowSettingsResponseUseCustomScript {
	return DaVinciFlowSettingsResponseUseCustomScript{
		DaVinciFlowSettingsResponseUseCustomScriptChoice2: v,
	}
}

// boolAsDaVinciFlowSettingsResponseUseCustomScript is a convenience function that returns bool wrapped in DaVinciFlowSettingsResponseUseCustomScript
func BoolAsDaVinciFlowSettingsResponseUseCustomScript(v *bool) DaVinciFlowSettingsResponseUseCustomScript {
	return DaVinciFlowSettingsResponseUseCustomScript{
		Bool: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *DaVinciFlowSettingsResponseUseCustomScript) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into DaVinciFlowSettingsResponseUseCustomScriptChoice2
	err = json.Unmarshal(data, &dst.DaVinciFlowSettingsResponseUseCustomScriptChoice2)
	if err == nil {
		jsonDaVinciFlowSettingsResponseUseCustomScriptChoice2, _ := json.Marshal(dst.DaVinciFlowSettingsResponseUseCustomScriptChoice2)
		if string(jsonDaVinciFlowSettingsResponseUseCustomScriptChoice2) == "{}" { // empty struct
			dst.DaVinciFlowSettingsResponseUseCustomScriptChoice2 = nil
		} else {
			match++
		}
	} else {
		dst.DaVinciFlowSettingsResponseUseCustomScriptChoice2 = nil
	}

	// try to unmarshal data into Bool
	err = json.Unmarshal(data, &dst.Bool)
	if err == nil {
		jsonBool, _ := json.Marshal(dst.Bool)
		if string(jsonBool) == "{}" { // empty struct
			dst.Bool = nil
		} else {
			match++
		}
	} else {
		dst.Bool = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.DaVinciFlowSettingsResponseUseCustomScriptChoice2 = nil
		dst.Bool = nil

		return fmt.Errorf("data matches more than one schema in oneOf(DaVinciFlowSettingsResponseUseCustomScript)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(DaVinciFlowSettingsResponseUseCustomScript)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src DaVinciFlowSettingsResponseUseCustomScript) MarshalJSON() ([]byte, error) {
	if src.DaVinciFlowSettingsResponseUseCustomScriptChoice2 != nil {
		return json.Marshal(&src.DaVinciFlowSettingsResponseUseCustomScriptChoice2)
	}

	if src.Bool != nil {
		return json.Marshal(&src.Bool)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *DaVinciFlowSettingsResponseUseCustomScript) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.DaVinciFlowSettingsResponseUseCustomScriptChoice2 != nil {
		return obj.DaVinciFlowSettingsResponseUseCustomScriptChoice2
	}

	if obj.Bool != nil {
		return obj.Bool
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj DaVinciFlowSettingsResponseUseCustomScript) GetActualInstanceValue() interface{} {
	if obj.DaVinciFlowSettingsResponseUseCustomScriptChoice2 != nil {
		return *obj.DaVinciFlowSettingsResponseUseCustomScriptChoice2
	}

	if obj.Bool != nil {
		return *obj.Bool
	}

	// all schemas are nil
	return nil
}

type NullableDaVinciFlowSettingsResponseUseCustomScript struct {
	value *DaVinciFlowSettingsResponseUseCustomScript
	isSet bool
}

func (v NullableDaVinciFlowSettingsResponseUseCustomScript) Get() *DaVinciFlowSettingsResponseUseCustomScript {
	return v.value
}

func (v *NullableDaVinciFlowSettingsResponseUseCustomScript) Set(val *DaVinciFlowSettingsResponseUseCustomScript) {
	v.value = val
	v.isSet = true
}

func (v NullableDaVinciFlowSettingsResponseUseCustomScript) IsSet() bool {
	return v.isSet
}

func (v *NullableDaVinciFlowSettingsResponseUseCustomScript) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDaVinciFlowSettingsResponseUseCustomScript(val *DaVinciFlowSettingsResponseUseCustomScript) *NullableDaVinciFlowSettingsResponseUseCustomScript {
	return &NullableDaVinciFlowSettingsResponseUseCustomScript{value: val, isSet: true}
}

func (v NullableDaVinciFlowSettingsResponseUseCustomScript) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDaVinciFlowSettingsResponseUseCustomScript) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
