// Copyright © 2025 Ping Identity Corporation
/*
PingOne Platform User and Configuration Management API - Go SDK

PingOne is a cloud-based framework for secure identity access management. The PingOne API gives developers the tools to integrate enterprise and third-party applications with the PingOne platform.

Contact: developerexperiences@pingidentity.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingone

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"time"
)

// checks if the DaVinciApplicationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DaVinciApplicationResponse{}

// checks if the DaVinciApplicationResponse type satisfies the LogValuer interface at compile time
var _ slog.LogValuer = &DaVinciApplicationResponse{}

// DaVinciApplicationResponse struct for DaVinciApplicationResponse
type DaVinciApplicationResponse struct {
	Links                DaVinciApplicationResponseLinks  `json:"_links"`
	ApiKey               DaVinciApplicationResponseApiKey `json:"apiKey"`
	Environment          ResourceRelationshipReadOnly     `json:"environment"`
	Id                   string                           `json:"id"`
	Name                 string                           `json:"name"`
	Oauth                DaVinciApplicationResponseOAuth  `json:"oauth"`
	CreatedAt            *time.Time                       `json:"createdAt,omitempty"`
	UpdatedAt            *time.Time                       `json:"updatedAt,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DaVinciApplicationResponse DaVinciApplicationResponse

// NewDaVinciApplicationResponse instantiates a new DaVinciApplicationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDaVinciApplicationResponse(links DaVinciApplicationResponseLinks, apiKey DaVinciApplicationResponseApiKey, environment ResourceRelationshipReadOnly, id string, name string, oauth DaVinciApplicationResponseOAuth) *DaVinciApplicationResponse {
	this := DaVinciApplicationResponse{}
	this.Links = links
	this.ApiKey = apiKey
	this.Environment = environment
	this.Id = id
	this.Name = name
	this.Oauth = oauth
	return &this
}

// NewDaVinciApplicationResponseWithDefaults instantiates a new DaVinciApplicationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDaVinciApplicationResponseWithDefaults() *DaVinciApplicationResponse {
	this := DaVinciApplicationResponse{}
	return &this
}

// GetLinks returns the Links field value
func (o *DaVinciApplicationResponse) GetLinks() DaVinciApplicationResponseLinks {
	if o == nil {
		var ret DaVinciApplicationResponseLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *DaVinciApplicationResponse) GetLinksOk() (*DaVinciApplicationResponseLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *DaVinciApplicationResponse) SetLinks(v DaVinciApplicationResponseLinks) {
	o.Links = v
}

// GetApiKey returns the ApiKey field value
func (o *DaVinciApplicationResponse) GetApiKey() DaVinciApplicationResponseApiKey {
	if o == nil {
		var ret DaVinciApplicationResponseApiKey
		return ret
	}

	return o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value
// and a boolean to check if the value has been set.
func (o *DaVinciApplicationResponse) GetApiKeyOk() (*DaVinciApplicationResponseApiKey, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiKey, true
}

// SetApiKey sets field value
func (o *DaVinciApplicationResponse) SetApiKey(v DaVinciApplicationResponseApiKey) {
	o.ApiKey = v
}

// GetEnvironment returns the Environment field value
func (o *DaVinciApplicationResponse) GetEnvironment() ResourceRelationshipReadOnly {
	if o == nil {
		var ret ResourceRelationshipReadOnly
		return ret
	}

	return o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value
// and a boolean to check if the value has been set.
func (o *DaVinciApplicationResponse) GetEnvironmentOk() (*ResourceRelationshipReadOnly, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Environment, true
}

// SetEnvironment sets field value
func (o *DaVinciApplicationResponse) SetEnvironment(v ResourceRelationshipReadOnly) {
	o.Environment = v
}

// GetId returns the Id field value
func (o *DaVinciApplicationResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DaVinciApplicationResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DaVinciApplicationResponse) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *DaVinciApplicationResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DaVinciApplicationResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DaVinciApplicationResponse) SetName(v string) {
	o.Name = v
}

// GetOauth returns the Oauth field value
func (o *DaVinciApplicationResponse) GetOauth() DaVinciApplicationResponseOAuth {
	if o == nil {
		var ret DaVinciApplicationResponseOAuth
		return ret
	}

	return o.Oauth
}

// GetOauthOk returns a tuple with the Oauth field value
// and a boolean to check if the value has been set.
func (o *DaVinciApplicationResponse) GetOauthOk() (*DaVinciApplicationResponseOAuth, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Oauth, true
}

// SetOauth sets field value
func (o *DaVinciApplicationResponse) SetOauth(v DaVinciApplicationResponseOAuth) {
	o.Oauth = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *DaVinciApplicationResponse) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DaVinciApplicationResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DaVinciApplicationResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *DaVinciApplicationResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *DaVinciApplicationResponse) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DaVinciApplicationResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *DaVinciApplicationResponse) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *DaVinciApplicationResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o DaVinciApplicationResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DaVinciApplicationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["_links"] = o.Links
	toSerialize["apiKey"] = o.ApiKey
	toSerialize["environment"] = o.Environment
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["oauth"] = o.Oauth
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DaVinciApplicationResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"_links",
		"apiKey",
		"environment",
		"id",
		"name",
		"oauth",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDaVinciApplicationResponse := _DaVinciApplicationResponse{}

	err = json.Unmarshal(data, &varDaVinciApplicationResponse)

	if err != nil {
		return err
	}

	*o = DaVinciApplicationResponse(varDaVinciApplicationResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "_links")
		delete(additionalProperties, "apiKey")
		delete(additionalProperties, "environment")
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "oauth")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

func (o DaVinciApplicationResponse) LogValue() slog.Value {
	logAttrs := make([]slog.Attr, 0)

	logAttrs = append(logAttrs, slog.Any("_links", o.Links))
	logAttrs = append(logAttrs, slog.Any("apiKey", o.ApiKey))
	logAttrs = append(logAttrs, slog.Any("environment", o.Environment))
	logAttrs = append(logAttrs, slog.Any("id", o.Id))
	logAttrs = append(logAttrs, slog.Any("name", o.Name))
	logAttrs = append(logAttrs, slog.Any("oauth", o.Oauth))
	if !IsNil(o.CreatedAt) {
		logAttrs = append(logAttrs, slog.Any("createdAt", *o.CreatedAt))
	}
	if !IsNil(o.UpdatedAt) {
		logAttrs = append(logAttrs, slog.Any("updatedAt", *o.UpdatedAt))
	}
	logAttrs = append(logAttrs, slog.Any("additionalProperties", o.AdditionalProperties))

	return slog.GroupValue(logAttrs...)
}

type NullableDaVinciApplicationResponse struct {
	value *DaVinciApplicationResponse
	isSet bool
}

func (v NullableDaVinciApplicationResponse) Get() *DaVinciApplicationResponse {
	return v.value
}

func (v *NullableDaVinciApplicationResponse) Set(val *DaVinciApplicationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDaVinciApplicationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDaVinciApplicationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDaVinciApplicationResponse(val *DaVinciApplicationResponse) *NullableDaVinciApplicationResponse {
	return &NullableDaVinciApplicationResponse{value: val, isSet: true}
}

func (v NullableDaVinciApplicationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDaVinciApplicationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
