// Copyright © 2025 Ping Identity Corporation
/*
PingOne Platform User and Configuration Management API - SDK Generator

PingOne is a cloud-based framework for secure identity access management. The PingOne API gives developers the tools to integrate enterprise and third-party applications with the PingOne platform.

Contact: devex@pingidentity.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingone

import (
	"encoding/json"
	"log/slog"
)

// checks if the DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema{}

// checks if the DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema type satisfies the LogValuer interface at compile time
var _ slog.LogValuer = &DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema{}

// DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema struct for DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema
type DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema struct {
	Value                *string `json:"value,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema

// NewDaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema instantiates a new DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema() *DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema {
	this := DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema{}
	return &this
}

// NewDaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchemaWithDefaults instantiates a new DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchemaWithDefaults() *DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema {
	this := DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema) SetValue(v string) {
	o.Value = &v
}

func (o DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema) UnmarshalJSON(data []byte) (err error) {

	varDaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema := _DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema{}

	err = json.Unmarshal(data, &varDaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema)

	if err != nil {
		return err
	}

	*o = DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema(varDaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

func (o DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema) LogValue() slog.Value {
	logAttrs := make([]slog.Attr, 0)

	if !IsNil(o.Value) {
		logAttrs = append(logAttrs, slog.Any("value", *o.Value))
	}
	logAttrs = append(logAttrs, slog.Any("additionalProperties", o.AdditionalProperties))

	return slog.GroupValue(logAttrs...)
}

type NullableDaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema struct {
	value *DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema
	isSet bool
}

func (v NullableDaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema) Get() *DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema {
	return v.value
}

func (v *NullableDaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema) Set(val *DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableDaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableDaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema(val *DaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema) *NullableDaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema {
	return &NullableDaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema{value: val, isSet: true}
}

func (v NullableDaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDaVinciFlowGraphDataResponseElementsNodeDataPropertiesInputSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
