// Copyright © 2025 Ping Identity Corporation
/*
PingOne Platform User and Configuration Management API - SDK Generator

PingOne is a cloud-based framework for secure identity access management. The PingOne API gives developers the tools to integrate enterprise and third-party applications with the PingOne platform.

Contact: devex@pingidentity.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingone

import (
	"encoding/json"
	"fmt"
)

// DaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2 the model 'DaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2'
type DaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2 string

// List of DaVinci_Flow_Settings_Request_Preview_Form_Rendering_Updates_Choice_2
const (
	DAVINCIFLOWSETTINGSREQUESTPREVIEWFORMRENDERINGUPDATESCHOICE2_FALSE DaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2 = "false"
	DAVINCIFLOWSETTINGSREQUESTPREVIEWFORMRENDERINGUPDATESCHOICE2_TRUE  DaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2 = "true"
)

// All allowed values of DaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2 enum
var AllowedDaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2EnumValues = []DaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2{
	"false",
	"true",
}

func (v *DaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2(value)
	for _, existing := range AllowedDaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2EnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = DaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2(fmt.Sprintf("%s", value))
	return nil
}

// NewDaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2FromValue returns a pointer to a valid DaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2FromValue(v string) (*DaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2, error) {
	ev := DaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2: valid values are %v", v, AllowedDaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2EnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2) IsValid() bool {
	for _, existing := range AllowedDaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2EnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DaVinci_Flow_Settings_Request_Preview_Form_Rendering_Updates_Choice_2 value
func (v DaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2) Ptr() *DaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2 {
	return &v
}

type NullableDaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2 struct {
	value *DaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2
	isSet bool
}

func (v NullableDaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2) Get() *DaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2 {
	return v.value
}

func (v *NullableDaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2) Set(val *DaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2) {
	v.value = val
	v.isSet = true
}

func (v NullableDaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2) IsSet() bool {
	return v.isSet
}

func (v *NullableDaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2(val *DaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2) *NullableDaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2 {
	return &NullableDaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2{value: val, isSet: true}
}

func (v NullableDaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDaVinciFlowSettingsRequestPreviewFormRenderingUpdatesChoice2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
