// Copyright © 2025 Ping Identity Corporation
/*
PingOne Platform User and Configuration Management API - Go SDK

PingOne is a cloud-based framework for secure identity access management. The PingOne API gives developers the tools to integrate enterprise and third-party applications with the PingOne platform.

Contact: developerexperiences@pingidentity.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingone

import (
	"encoding/json"
	"log/slog"
)

// checks if the TotalIdentitiesCountCollectionResponseLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TotalIdentitiesCountCollectionResponseLinks{}

// checks if the TotalIdentitiesCountCollectionResponseLinks type satisfies the LogValuer interface at compile time
var _ slog.LogValuer = &TotalIdentitiesCountCollectionResponseLinks{}

// TotalIdentitiesCountCollectionResponseLinks struct for TotalIdentitiesCountCollectionResponseLinks
type TotalIdentitiesCountCollectionResponseLinks struct {
	Self                 *JSONHALLink `json:"self,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TotalIdentitiesCountCollectionResponseLinks TotalIdentitiesCountCollectionResponseLinks

// NewTotalIdentitiesCountCollectionResponseLinks instantiates a new TotalIdentitiesCountCollectionResponseLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTotalIdentitiesCountCollectionResponseLinks() *TotalIdentitiesCountCollectionResponseLinks {
	this := TotalIdentitiesCountCollectionResponseLinks{}
	return &this
}

// NewTotalIdentitiesCountCollectionResponseLinksWithDefaults instantiates a new TotalIdentitiesCountCollectionResponseLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTotalIdentitiesCountCollectionResponseLinksWithDefaults() *TotalIdentitiesCountCollectionResponseLinks {
	this := TotalIdentitiesCountCollectionResponseLinks{}
	return &this
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *TotalIdentitiesCountCollectionResponseLinks) GetSelf() JSONHALLink {
	if o == nil || IsNil(o.Self) {
		var ret JSONHALLink
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TotalIdentitiesCountCollectionResponseLinks) GetSelfOk() (*JSONHALLink, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *TotalIdentitiesCountCollectionResponseLinks) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given JSONHALLink and assigns it to the Self field.
func (o *TotalIdentitiesCountCollectionResponseLinks) SetSelf(v JSONHALLink) {
	o.Self = &v
}

func (o TotalIdentitiesCountCollectionResponseLinks) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TotalIdentitiesCountCollectionResponseLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TotalIdentitiesCountCollectionResponseLinks) UnmarshalJSON(data []byte) (err error) {
	varTotalIdentitiesCountCollectionResponseLinks := _TotalIdentitiesCountCollectionResponseLinks{}

	err = json.Unmarshal(data, &varTotalIdentitiesCountCollectionResponseLinks)

	if err != nil {
		return err
	}

	*o = TotalIdentitiesCountCollectionResponseLinks(varTotalIdentitiesCountCollectionResponseLinks)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "self")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

func (o TotalIdentitiesCountCollectionResponseLinks) LogValue() slog.Value {
	logAttrs := make([]slog.Attr, 0)

	if !IsNil(o.Self) {
		logAttrs = append(logAttrs, slog.Any("self", *o.Self))
	}
	logAttrs = append(logAttrs, slog.Any("additionalProperties", o.AdditionalProperties))

	return slog.GroupValue(logAttrs...)
}

type NullableTotalIdentitiesCountCollectionResponseLinks struct {
	value *TotalIdentitiesCountCollectionResponseLinks
	isSet bool
}

func (v NullableTotalIdentitiesCountCollectionResponseLinks) Get() *TotalIdentitiesCountCollectionResponseLinks {
	return v.value
}

func (v *NullableTotalIdentitiesCountCollectionResponseLinks) Set(val *TotalIdentitiesCountCollectionResponseLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableTotalIdentitiesCountCollectionResponseLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableTotalIdentitiesCountCollectionResponseLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTotalIdentitiesCountCollectionResponseLinks(val *TotalIdentitiesCountCollectionResponseLinks) *NullableTotalIdentitiesCountCollectionResponseLinks {
	return &NullableTotalIdentitiesCountCollectionResponseLinks{value: val, isSet: true}
}

func (v NullableTotalIdentitiesCountCollectionResponseLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTotalIdentitiesCountCollectionResponseLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
