// Copyright © 2025 Ping Identity Corporation
/*
PingOne Platform User and Configuration Management API - Go SDK

PingOne is a cloud-based framework for secure identity access management. The PingOne API gives developers the tools to integrate enterprise and third-party applications with the PingOne platform.

Contact: developerexperiences@pingidentity.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingone

import (
	"encoding/json"
	"fmt"
)

// DaVinciFlowResponseOutputSchemaOutputType the model 'DaVinciFlowResponseOutputSchemaOutputType'
type DaVinciFlowResponseOutputSchemaOutputType string

// List of DaVinci_Flow_Response_Output_Schema_Output_Type
const (
	DAVINCIFLOWRESPONSEOUTPUTSCHEMAOUTPUTTYPE_OBJECT DaVinciFlowResponseOutputSchemaOutputType = "object"
)

// All allowed values of DaVinciFlowResponseOutputSchemaOutputType enum
var AllowedDaVinciFlowResponseOutputSchemaOutputTypeEnumValues = []DaVinciFlowResponseOutputSchemaOutputType{
	"object",
}

func (v *DaVinciFlowResponseOutputSchemaOutputType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DaVinciFlowResponseOutputSchemaOutputType(value)
	for _, existing := range AllowedDaVinciFlowResponseOutputSchemaOutputTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = DaVinciFlowResponseOutputSchemaOutputType(fmt.Sprintf("%s", value))
	return nil
}

// NewDaVinciFlowResponseOutputSchemaOutputTypeFromValue returns a pointer to a valid DaVinciFlowResponseOutputSchemaOutputType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDaVinciFlowResponseOutputSchemaOutputTypeFromValue(v string) (*DaVinciFlowResponseOutputSchemaOutputType, error) {
	ev := DaVinciFlowResponseOutputSchemaOutputType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DaVinciFlowResponseOutputSchemaOutputType: valid values are %v", v, AllowedDaVinciFlowResponseOutputSchemaOutputTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DaVinciFlowResponseOutputSchemaOutputType) IsValid() bool {
	for _, existing := range AllowedDaVinciFlowResponseOutputSchemaOutputTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DaVinci_Flow_Response_Output_Schema_Output_Type value
func (v DaVinciFlowResponseOutputSchemaOutputType) Ptr() *DaVinciFlowResponseOutputSchemaOutputType {
	return &v
}

type NullableDaVinciFlowResponseOutputSchemaOutputType struct {
	value *DaVinciFlowResponseOutputSchemaOutputType
	isSet bool
}

func (v NullableDaVinciFlowResponseOutputSchemaOutputType) Get() *DaVinciFlowResponseOutputSchemaOutputType {
	return v.value
}

func (v *NullableDaVinciFlowResponseOutputSchemaOutputType) Set(val *DaVinciFlowResponseOutputSchemaOutputType) {
	v.value = val
	v.isSet = true
}

func (v NullableDaVinciFlowResponseOutputSchemaOutputType) IsSet() bool {
	return v.isSet
}

func (v *NullableDaVinciFlowResponseOutputSchemaOutputType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDaVinciFlowResponseOutputSchemaOutputType(val *DaVinciFlowResponseOutputSchemaOutputType) *NullableDaVinciFlowResponseOutputSchemaOutputType {
	return &NullableDaVinciFlowResponseOutputSchemaOutputType{value: val, isSet: true}
}

func (v NullableDaVinciFlowResponseOutputSchemaOutputType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDaVinciFlowResponseOutputSchemaOutputType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
