// Copyright © 2025 Ping Identity Corporation
/*
PingOne Platform User and Configuration Management API - Go SDK

PingOne is a cloud-based framework for secure identity access management. The PingOne API gives developers the tools to integrate enterprise and third-party applications with the PingOne platform.

Contact: developerexperiences@pingidentity.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pingone

import (
	"encoding/json"
	"fmt"
)

// EnvironmentStatusValue the model 'EnvironmentStatusValue'
type EnvironmentStatusValue string

// List of EnvironmentStatusValue
const (
	ENVIRONMENTSTATUSVALUE_ACTIVE         EnvironmentStatusValue = "ACTIVE"
	ENVIRONMENTSTATUSVALUE_DELETE_PENDING EnvironmentStatusValue = "DELETE_PENDING"
)

// All allowed values of EnvironmentStatusValue enum
var AllowedEnvironmentStatusValueEnumValues = []EnvironmentStatusValue{
	"ACTIVE",
	"DELETE_PENDING",
}

func (v *EnvironmentStatusValue) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EnvironmentStatusValue(value)
	for _, existing := range AllowedEnvironmentStatusValueEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = EnvironmentStatusValue(fmt.Sprintf("%s", "UNKNOWN"))
	return nil
}

// NewEnvironmentStatusValueFromValue returns a pointer to a valid EnvironmentStatusValue
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEnvironmentStatusValueFromValue(v string) (*EnvironmentStatusValue, error) {
	ev := EnvironmentStatusValue(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EnvironmentStatusValue: valid values are %v", v, AllowedEnvironmentStatusValueEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EnvironmentStatusValue) IsValid() bool {
	for _, existing := range AllowedEnvironmentStatusValueEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EnvironmentStatusValue value
func (v EnvironmentStatusValue) Ptr() *EnvironmentStatusValue {
	return &v
}

type NullableEnvironmentStatusValue struct {
	value *EnvironmentStatusValue
	isSet bool
}

func (v NullableEnvironmentStatusValue) Get() *EnvironmentStatusValue {
	return v.value
}

func (v *NullableEnvironmentStatusValue) Set(val *EnvironmentStatusValue) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentStatusValue) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentStatusValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentStatusValue(val *EnvironmentStatusValue) *NullableEnvironmentStatusValue {
	return &NullableEnvironmentStatusValue{value: val, isSet: true}
}

func (v NullableEnvironmentStatusValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentStatusValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
