name: Go Tests

on:
  push:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/go-test.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/go-test.yml'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Get dependencies
      run: go mod download

    - name: Run unit tests
      run: go test ./config/... ./oauth2/... ./oidc/... -v

    # Optionally enable this test when the credentials are properly setup
    # - name: Run integration tests
    #   run: go test ./pingone/... -v
    #   env:
    #     PINGONE_USERNAME: ${{ secrets.PINGONE_USERNAME }}
    #     PINGONE_PASSWORD: ${{ secrets.PINGONE_PASSWORD }}
    #     PINGONE_CLIENT_ID: ${{ secrets.PINGONE_CLIENT_ID }}
    #     PINGONE_CLIENT_SECRET: ${{ secrets.PINGONE_CLIENT_SECRET }}
    #     PINGONE_ENVIRONMENT_ID: ${{ secrets.PINGONE_ENVIRONMENT_ID }}
